version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 portofolio.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=your_secret_key_here
      - ALLOWED_HOSTS=localhost,127.0.0.1

volumes:
  static_volume: